package escape.room.game.gameobject;

public enum DuodecimalCycle {
	DUODECIMAL_CYCLE1, DUODECIMAL_CYCLE2, DUODECIMAL_CYCLE3, DUODECIMAL_CYCLE4, DUODECIMAL_CYCLE5, DUODECIMAL_CYCLE6, DUODECIMAL_CYCLE7, DUODECIMAL_CYCLE8, DUODECIMAL_CYCLE9, DUODECIMAL_CYCLE10, DUODECIMAL_CYCLE11, DUODECIMAL_CYCLE12
}
